# deploy/nginx.conf
server {
    listen 80;
    server_name naveennallanti.com www.naveennallanti.com;

    location /api/ {
        client_max_body_size 2m;
        proxy_pass http://127.0.0.1:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
        alias /var/www/danielsphysiotherapy/backend/src/uploads/;
    }

    location / {
        root /var/www/danielsphysiotherapy/frontend/dist;
        try_files $uri /index.html;
    }
}
